env:
  browser: true
  es6: true

root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2020
  sourceType: module
ignorePatterns:
  - '/node_modules/'
rules:
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-empty-function': 'off'
  '@typescript-eslint/no-unused-vars': [error, {vars: all, args: none}]
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/ban-ts-comment': 'off'
