name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  lint-and-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Npm setup
        run: npm install

      - name: Lint
        run: npm run lint
